name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test
      - run: bun run build
      - run: |
          echo '@ricsam:registry=https://registry.npmjs.org' >> .npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          echo '//registry.npmjs.org/:always-auth=true' >> .npmrc
      - name: changeset publish
        run: npx changeset publish --access=public --registry=https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
